### ISSUE TITLE
Consolidate env variables

### ISSUE THREAD

**Issue by neoformit** [usegalaxy-eu/WallE#9]
This just needs to be done when PRs have merged...

For walle's env vars we will have:

```yml
walle_envs_database: []
walle_envs_user_deletion: []
walle_envs_slack: []
```

These should all be customizable with:

```yml
walle_extra_env_vars: []
``` 

But for this to happen, we need the Ansible tasks to ordered correctly, maybe like:

```yml
# defaults.yml
walle_env_vars: "{{ walle_envs_database + walle_envs_user_deletion + walle_envs_slack }}"
```

```yml
# tasks.yml
- name: Add walle_env_vars to walle_bashrc
  ansible.builtin.lineinfile:
    path: "{{ walle_bashrc }}"
    regexp: "^export {{ item.key }}="
    line: 'export {{ item.key }}="{{ item.value }}"'
  with_items: "{{ walle_env_vars }}"

- name: Extend walle_bashrc with user-defined walle_extra_env_vars
  ansible.builtin.lineinfile:
    path: "{{ walle_bashrc }}"
    regexp: "^export {{ item.key }}="
    line: 'export {{ item.key }}="{{ item.value }}"'
  with_items: "{{ walle_extra_env_vars }}"
  when: walle_extra_env_vars
```

Or even all in one task. But I think the above makes it a little more clear what is happening.
